name: Shopify Store Watcher
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ master ]
jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - id: Deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with: 
        name: shopify-shop-watcher
        runtime: nodejs14
        region: ${{ secrets.GCP_DEPLOY_REGION }}
        entry_point: ${{ secrets.GCP_ENTRY_POINT }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id : ${{ secrets.GCP_PROJECT_ID }}
        timeout: 540
        env_vars: 
          DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }},SHOPIFY_SHOP_NAME=${{ secrets.SHOPIFY_SHOP_NAME }},SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }},SHOPIFY_API_PASSWORD=${{ secrets.SHOPIFY_API_PASSWORD }}